/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mitumc.mnemonicexj;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
    }
}
